# Generated by Django 4.1.1 on 2022-09-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=254, unique=True, verbose_name="书籍名称"),
                ),
                ("pub_date", models.DateField(null=True, verbose_name="发布时间")),
                ("read_count", models.IntegerField(default=0, verbose_name="阅读数量")),
                ("comment_count", models.IntegerField(default=0, verbose_name="评论数量")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={"verbose_name": "书籍信息", "db_table": "book_info",},
        ),
        migrations.CreateModel(
            name="MemberInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, verbose_name="成员姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "male"), (1, "female")], verbose_name="性别"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, null=True, verbose_name="作者简介"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.bookinfo",
                        verbose_name="关联书籍",
                    ),
                ),
            ],
            options={"verbose_name": "成员信息", "db_table": "author_info",},
        ),
    ]
