# Generated by Django 4.1.1 on 2022-09-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberinfo", old_name="book_id", new_name="book",
        ),
        migrations.AlterModelTable(name="memberinfo", table="mumber_info",),
    ]
